# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 23:44
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('shop', models.CharField(max_length=255)),
                ('rating_score', models.FloatField()),
                ('rating_count', models.IntegerField()),
                ('price', models.FloatField()),
                ('price_currency', models.FloatField()),
                ('available', models.BooleanField()),
                ('views', models.IntegerField()),
                ('imgs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('description', models.TextField()),
            ],
        ),
    ]
