# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etsy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_currency',
            field=models.CharField(max_length=10),
        ),
    ]
