# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etsy', '0002_auto_20151206_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating_score',
            field=models.FloatField(null=True),
        ),
    ]
